version: '3.9'
services:
  api:
    env_file: ./api/.env.dev
    container_name: resources_api
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  
  web:
    container_name: resources_web
    restart: unless-stopped
    build: 
      context: ./sys-stats
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - api