name: Build Image - System Resource Viewer API

on: workflow_dispatch
#   push:
#     branches: main
#     paths:
#       - api/**

env:
  IMAGE_REPO: sys-resource-view-api

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
      
#     - name: Bash Action
#       run: "pwd ; ls -al"
          
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./api/
        file: ./api/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_REPO:${{ github.sha }}
          ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_REPO:latest
    
