name: Build Image - System Resource Viewer WEB

on: workflow_dispatch
#   push:
#     branches: main
#     paths:
#       - sys-stats/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
      
#     - name: Bash Action
#       run: "pwd ; ls -al"
          
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./sys-stats/
        file: ./sys-stats/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/sys-resource-view-web:${{ github.sha }}
          ${{ secrets.DOCKERHUB_USERNAME }}/sys-resource-view-web:latest
    
